### ISSUE TITLE
Error: Unexpected token { when building for ios

### ISSUE THREAD

**Issue by kellycampbell** [raphinesse/cordova-plugin-exclude-files#3]
We are receiving this error when running `cordova -d prepare` on MacOS for an iOS platform. 0.2.2 of this plugin works. this error started in 0.2.3

```
Prepared iOS project successfully
Executing script found in plugin cordova-plugin-exclude-files for hook "after_prepare": plugins/cordova-plugin-exclude-files/scripts/exclude-files.js
Error: Unexpected token {
```

**Comment by raphinesse** [comment]
Thanks for reporting. Which version of `cordova` and `node` are you using? Does the error message give details about the location of the error?

**Comment by kellycampbell** [comment]
It didn't give an exact location. I'm guessing it's the new const stuff at
the top due to ES6 not available on all devices or browser types.

**Comment by raphinesse** [comment]
Yes, I suspect that I unknowingly have increased the required node version by using that destructuring assignment. This plugin operates only at build time, using `node` scripts. So it does not depend on device/browser support for specific features.

That's why I only asked which version of node you were using.

**Comment by raphinesse** [comment]
Can confirm that v0.2.3 does not work with node versions less than 6. Since [these versions will have reached their end of life by end of this April](https://github.com/nodejs/Release), I will no longer support them in newer versions.

Starting from v0.3.0, node 6 is required to use this plugin. If you need support for older node versions, please use `cordova-plugin-exclude-files@^0.2.4`. v0.2.4 is identical to v0.2.2.

That should fix this issue. If not, please let me know, so I can reopen it.
